apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
---  
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
  - name: backend-service-container
    image: gporras/chat-socket-broker:latest
    ports:
    - containerPort: 8080
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: pdn
    - name: MONGO_HOST
      value: mongo-service:27017
    - name: MONGO_PORT
      value: "27017"
    - name: MONGO_USERNAME
      value: devuser
    - name: MONGO_PASSWORD
      value: devpassword
