apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: challenge-ns
spec:
  type: NodePort
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gporras/chat-socket-front:latest
          env:
            - name: API_URL
              value: "http://backend-service:8080/chat-websocket"
          ports:
            - containerPort: 80