apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo 
spec:
  containers:
  - name: mongo
    image: mongo:4.4
    env:
      - name: TZ
        value: America/Bogota
      - name: MONGO_INITDB_ROOT_USERNAME
        value: devuser
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: devpassword
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: /data/db
      name: mongo-data
  volumes:
  - name: mongo-data
    hostPath:
      path: /path/to/your/mongodata
